### PR TITLE
Version bump to 0.51.3

### PR DESCRIPTION
**Pull request by alexsm20**

### CODE REVIEW

**Review by udaypatial — APPROVED** [review]

**Comment by bhaumiik** [comment]
Should this be done through https://github.com/scorebet/apollo-ios/blob/connect/Configuration/Shared/Project-Version.xcconfig?

**Comment by alexsm20** [comment]
> Should this be done through https://github.com/scorebet/apollo-ios/blob/connect/Configuration/Shared/Project-Version.xcconfig?

Ohh, good call! I wasn't sure how it was being set before

**Comment by bhaumiik** [comment]
LGTM 👍 I checked merged PRs and seems like we generally keep the version in sync with apollo-ios repo. Not sure what would be the process on forked repo here after the fix. Let's wait for @ketenshi or @tahirmt to weigh in on this.

**Comment by tahirmt** [comment]
Honestly we shouldn’t be bumping version of the fork. We will need to update this to 0.53.0 soon.

**Comment by alexsm20** [comment]
> Honestly we shouldn’t be bumping version of the fork. We will need to update this to 0.53.0 soon.

Interesting point.

**Comment by ketenshi** [comment]
Yea let's just create a new tag instead with the new commit. Maybe `connect-0.51.2a` or just ``connect-0.51.3`?

**Comment by alexsm20** [comment]
Closing this PR and will just do a new tag `connect-0.51.2a`. After all, it's just a version number.

**Pull request closed without merging**
