### PR TITLE
Update to 0.51.2

### PR DESCRIPTION
**Pull request by GlobakMaxim**
Update the connect branch to 0.51.2 version from upstream

### CODE REVIEW

**Review by tahirmt — APPROVED** [review]

**Comment by ketenshi** [comment]
Has this been tested against https://github.com/scorebet/ios-graphql-client ?
There's a lot of deletions so I'm a bit wary of that, also I'm not seeing any of our commits anymore

**Comment by ketenshi** [comment]
Compared to this PR where our commits are at the end https://github.com/scorebet/apollo-ios/pull/13/commits

**Comment by tahirmt** [comment]
Yeah I just realized that in the past we've always rebased these branches so that our commits are at the top and each of these branches should have our commits since we keep the version branches around

**Comment by GlobakMaxim** [comment]
@ketenshi @tahirmt Rebased this PR, our changes are there :) 
Also tested in ios-graphql-client, with small changes it works, all tests are green.

**Comment by tahirmt** [comment]
@GlobakMaxim that's not exactly what we were thinking. You don't need to rebase their commits. The idea is to pull the changes from apollo 0.51.2 and then rebase only the changes from our `connect` branch onto it.

**Comment by tahirmt** [comment]
Because if we merge this now we'll end up with commit signatures that's different from the source repo

**Comment by GlobakMaxim** [comment]
@tahirmt so I need to pull 0.51.2 again from the root repository, then in `connect` branch do `git rebase -i connect-0.51.2`?
Upd:
hmm... I think I need to branch off `connect` and rebase it with `master/main` from the root repository? or it would be the same?

**Comment by tahirmt** [comment]
@ketenshi how do we normally do this again? I forget. I know our way isn't the most ideal but we want our commits to be at the top so what do we normally do?

**Comment by ketenshi** [comment]
This is how i did it
> This will update our connect branch to the latest Apollo version.

> I created this branch from connect then rebased on the 0.47.1 tag. Afterwards I had to merge connect back into this branch

https://github.com/scorebet/apollo-ios/pull/12

**Pull request closed without merging**
