### PR TITLE
BET-4061: Apollo 0.23.1

### PR DESCRIPTION
**Pull request by ketenshi**
Updated Apollo Version
Release notes: https://github.com/apollographql/apollo-ios/releases

They made some fixes to the Watcher and Caching, which should fix some issues we are currently facing.

---

Created this branch off `connect` and then rebased on top of `upstream/master`

Afterwards merged `connect` into this branch.

No new merge conflicts other than from the commits we had before.

### CODE REVIEW

**Comment by ketenshi** [comment]
@scorebet/ios-team 

Hey guys, wanted to have some opinions on how to maintain this fork. 

I jotted down how I created this PR in the details. Another method I found is through cherry-picking our own commits as detailed here. https://die-antwort.eu/techblog/2016-08-git-tricks-for-maintaining-a-long-lived-fork/. 

I think it would be nice to keep our own commits as the last ones for readability, but I guess we can always use `git log --author` or something.

What do you guys think?

**Comment by tapi** [comment]
do we have documentation on why the for exists? are the changes we can send up stream and abandon the fork altogether?

**Comment by tapi** [comment]
I don't know if we've added other changes but it looks like the delta is pretty small

https://github.com/apollographql/apollo-ios/compare/master...delannoyk:connect#diff-f02d32650dd952f6c899b1123d26f007R81-R93

**Comment by tapi** [comment]
Looks like ping has been added upstream https://github.com/apollographql/apollo-ios/blob/995219c48d14672f5ea8cdb53304b51a2a8b8013/Sources/ApolloWebSocket/WebSocketTransport.swift#L104-L106

**Comment by ketenshi** [comment]
I think this would be more accurate: https://github.com/apollographql/apollo-ios/compare/master...scorebet:connect

We should be bypassing Kevin's fork.

**Comment by tapi** [comment]
yeah was wondering what the initial change set was

**Comment by tapi** [comment]
The list of commits gives us a rough idea of what changed and why, I still think we should make PRs for the ones that are reasonable to have merged upstream.

It takes the support burden off of us, makes future updates easier and produces greater visibility in the community as OSS contributors which Hechm seemed keen on in the last leads meeting.

I think exposing SSL for pinning is an easy one to get merged.

**Comment by tapi** [comment]
If anyones ever wondered why I focus so much on the why rather than what for code comments and commit messages this is why. 

https://github.com/apollographql/apollo-ios/commit/740a9b13f16defe2515559b15b72b2810282b440

what was done is obvious, why it was done is not.

**Comment by ketenshi** [comment]
I agree some of these changes could be pushed upstream. We do rely on Apollo a lot especially in the Betting projects so we could potentially be a big contributor.

We'll have to comb through our changes. I think some might not be required anymore depending on the changes to Apollo.

There's PRs like https://github.com/apollographql/apollo-ios/pull/1037 which had a quick approval time so that's promising.

**Comment by tapi** [comment]
agreed, Also curios why we have connect/disconnect and the socket public

**Comment by ketenshi** [comment]
We connect/disconnect when we update the auth token. Otherwise from what I remember we'll have to create a new `ApolloClient` each time.

**Comment by tapi** [comment]
and that is dependency injected all the way down so sending a new one is a PITA.

LOL. we don't use the methods we added. we use the exposed web socket directly

```swift
private func disconnectWebsockets(reconnect: Bool = false) {
        let websockets = queryRouter.endpoints.compactMap { $0.websocketTransport?.websocket as? WebSocket }
        websockets.forEach { $0.disconnect() }
        if reconnect {
            websockets.forEach { $0.connect() }
        }
    }
```

**Comment by ketenshi** [comment]
Lol we can discard that change then.

**Comment by tapi** [comment]
And it looks like that is the only time we use `websocket` so it's likely the methods would be sufficient and probably an easier sell upstream.

**Comment by tapi** [comment]
I wonder if instead of connect/disconnect we can use the existing `close` and add `reopen` seems like maybe that would solve our use of `refreshInterval` as well

**Comment by ketenshi** [comment]
Looking at their `closeConnection()` it sends a termination message to the server and clears out subscriptions and queues. I think we'll need to do some investigation and testing there as a separate PR.

**Comment by ketenshi** [comment]
Created https://jira.thescore.com/browse/BET-4109 to track pushing the changes upstream

**Pull request merged**
